projection:
  lon0: 121.000000
  lat0: 22.000000

world:
  arrive_radius_m: 4.0
  safety_margin_m: 4.0

planner:
  grid_res_m: 2.0
  diag_cost: 1.41421356237
  replan_min_interval_s: 0.3

speed:
  v_max_knots: 6.0
  a_lat_max: 0.4
  stop_slowdown_m: 12.0
